name: Actions Workflow
on: [push, pull_request]
jobs:
  nessus-tentools-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # setup docker
      - name: Download and startup the container
        run: docker run -p 8834:8834 --hostname nessus --name nessus -d sometheycallme/docker-nessus

      - name: Write nessus license from secrets to disk
        run: 'echo "$NLICENSE" > /tmp/nessus.license'
        shell: bash
        env:
          NLICENSE: ${{secrets.LICENSE}}

      # time to party
      - name: Install required PowerShell Modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSFramework, PoshRSJob -ErrorAction Stop
          
      - name: Initialize the nessus server with admin user and license
        shell: pwsh
        run: |
          Import-Module ./tentools.psd1
          $cred = New-Object -TypeName PSCredential -ArgumentList "admin", (ConvertTo-SecureString -String admin123 -AsPlainText -Force)
          $splat = @{
            ComputerName = "localhost"
            Credential = $cred
            EnableException = $true
            LicensePath = "/tmp/nessus.license"
            AcceptSelfSignedCert = $true
          }
          Initialize-TenServer @splat

      - name: Sleep to give Nessus time to initialize
        shell: pwsh
        run: Start-Sleep 20

      - name: Run Pester tests
        shell: pwsh
        run: |
          ./tests/pester.ps1
